version: '3.7'
services:
  profile:
    build:
      context: .
      target: base
    ports: 
      - "8080:8080"
    volumes:
      - .:/app/
    command: sh -c "yarn --audit && yarn build && yarn start"
