version: '3.7'
services:
  gateway:
    build:
      context: .
      target: base
    command: sh -c "yarn && yarn build && (yarn watch:server & yarn watch & wait)"
    environment:
      - PORT=8080
      - ENVIRONMENT=development
    ports:
      - "8080:8080"
    volumes:
      - .:/app/
