version: '3.7'
services:
  gateway:
    build:
      context: .
      target: base
    command: sh -c "yarn && yarn build && (yarn watch:server & yarn watch & wait)"
    environment:
      - IS_DOCKER=true
      - PORT=${PORT}
      - ENVIRONMENT={ENVIRONMENT}
      - IDAPI_CLIENT_ACCESS_TOKEN=${IDAPI_CLIENT_ACCESS_TOKEN}
      - IDAPI_BASE_URL=${IDAPI_BASE_URL}
      - PLAY_SESSION_COOKIE_SECRET=${PLAY_SESSION_COOKIE_SECRET}
      - BASE_URI=${BASE_URI}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app/
