version: '3.7'
services:
  gateway:
    build:
      context: .
      target: base
    command: sh -c "yarn && yarn build && (yarn watch:server & yarn watch & wait)"
    environment:
      - PORT=${PORT}
      - ENVIRONMENT={ENVIRONMENT}
      - IDAPI_CLIENT_ACCESS_TOKEN=${IDAPI_CLIENT_ACCESS_TOKEN}
      - IDAPI_BASE_URL=${IDAPI_BASE_URL}
      - PLAY_SESSION_COOKIE_SECRET=${PLAY_SESSION_COOKIE_SECRET}
      - BASE_URI=${BASE_URI}
      - DEFAULT_RETURN_URI=${DEFAULT_RETURN_URI}
      - STAGE=${STAGE}
      - SIGN_IN_PAGE_URL=${SIGN_IN_PAGE_URL}
      - IS_HTTPS=${IS_HTTPS}
      - APP_SECRET=${APP_SECRET}
      - GOOGLE_RECAPTCHA_SITE_KEY=${GOOGLE_RECAPTCHA_SITE_KEY}
      - GOOGLE_RECAPTCHA_SECRET_KEY=${GOOGLE_RECAPTCHA_SECRET_KEY}
      - ENCRYPTION_SECRET_KEY=${ENCRYPTION_SECRET_KEY}
      - OAUTH_BASE_URL=${OAUTH_BASE_URL}
      - OKTA_ORG_URL=${OKTA_ORG_URL}
      - OKTA_API_TOKEN=${OKTA_API_TOKEN}
      - OKTA_CUSTOM_OAUTH_SERVER=${OKTA_CUSTOM_OAUTH_SERVER}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_CLIENT_SECRET=${OKTA_CLIENT_SECRET}
    ports:
      - '${PORT}:${PORT}'
      - '9229:9229' # debugging port
    volumes:
      - .:/app/
      - ~/.aws/credentials:/root/.aws/credentials:ro
