version: '3.7'
services:
  profile:
    build:
      context: .
      target: base
    command: sh -c "yarn --audit && yarn build && (yarn watch:server & yarn watch & wait)"
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app/
