name: CI
on: push
jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions:
      # required by guardian/actions-assume-aws-role
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: guardian/actions-assume-aws-role@v1.0.0
        with:
          awsRoleToAssume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: ./ci.sh
