name: CI
on: push
jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions:
      # required by aws-actions/configure-aws-credentials
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Build
        run: yarn build
      - name: Calculate build number
        env:
          NUM: ${{ github.run_number }}
        run: |
          echo "GITHUB_RUN_NUMBER_WITH_OFFSET=$(($NUM + 5000))" >> $GITHUB_ENV
      - name: Riff Raff
        uses: guardian/actions-riff-raff@v2
        with:
          projectName: identity:identity-gateway
          buildNumber: ${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}
          configPath: riff-raff.yaml
          contentDirectories: |
            gateway-cloudformation:
              - cloudformation.yaml
            identity-gateway:
              - build
