name: Cypress Tests
on:
  push:
    branches:
      - main
  pull_request:
    types: ['review_requested']
  workflow_dispatch:
jobs:
  build:
    name: Build Gateway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build project
        run: pnpm run build
      - name: 'Zip build'
        run: zip -r -q build.zip ./build
      - name: 'Upload build'
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.zip
          retention-days: 1
  cypress-mocked:
    needs: build
    uses: ./.github/workflows/cypress-mocked.yml
    secrets: inherit
  cypress-mocked-okta:
    needs: build
    uses: ./.github/workflows/cypress-mocked-okta.yml
    secrets: inherit
  cypress-ete:
    needs: build
    uses: ./.github/workflows/cypress-ete.yml
    secrets: inherit
  cypress-ete-okta:
    needs: build
    uses: ./.github/workflows/cypress-ete-okta.yml
    secrets: inherit
