name: cypress-ete
on: push
jobs:
  cypress-ete:
    name: Cypress (ete)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          PORT: 8861
          NODE_ENV: development
          ENVIRONMENT: production
          STAGE: CODE
          BASE_URI: localhost:8861
          IDAPI_CLIENT_ACCESS_TOKEN: ${{ secrets.IDAPI_CLIENT_ACCESS_TOKEN }}
          IDAPI_BASE_URL: https://idapi.code.dev-theguardian.com
          PLAY_SESSION_COOKIE_SECRET: ${{ secrets.PLAY_SESSION_COOKIE_SECRET }}
          DEFAULT_RETURN_URI: https://m.code.dev-theguardian.com
          CYPRESS_DEFAULT_RETURN_URI: https://m.code.dev-theguardian.com
          SIGN_IN_PAGE_URL: https://profile.code.dev-theguardian.com/signin
          CYPRESS_SIGN_IN_PAGE_URL: https://profile.code.dev-theguardian.com/signin
          IS_HTTPS: false
          APP_SECRET: ${{ secrets.APP_SECRET }}
          CYPRESS_MAILSLURP_KEY: ${{ secrets.CYPRESS_MAILSLURP_KEY }}
        with:
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:8861/healthcheck'
          wait-on-timeout: 180
          quiet: true
          browser: chrome
          spec: cypress/integration/ete/*.js
