name: cypress-mocked
on: push
jobs:
  cypress-mocked:
    name: Cypress (mocked)
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps Redis port 6379 on service container to the host
          - 6379:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          PORT: 8861
          ENVIRONMENT: production
          STAGE: DEV
          BASE_URI: localhost:8861
          IDAPI_CLIENT_ACCESS_TOKEN: fakekey
          IDAPI_BASE_URL: http://localhost:9000
          DEFAULT_RETURN_URI: https://m.code.dev-theguardian.com
          CYPRESS_DEFAULT_RETURN_URI: https://m.code.dev-theguardian.com
          SIGN_IN_PAGE_URL: https://profile.code.dev-theguardian.com/signin
          OAUTH_BASE_URL: https://oauth.code.dev-theguardian.com
          CYPRESS_SIGN_IN_PAGE_URL: https://profile.code.dev-theguardian.com/signin
          IS_HTTPS: false
          APP_SECRET: devsecret
          CYPRESS_MAILOSAUR_API_KEY: ${{ secrets.CYPRESS_MAILOSAUR_API_KEY }}
          CYPRESS_MAILOSAUR_SERVER_ID: ${{ secrets.CYPRESS_MAILOSAUR_SERVER_ID }}
          # These are public test keys provided by Google for testing.
          # https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do
          GOOGLE_RECAPTCHA_SITE_KEY: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
          GOOGLE_RECAPTCHA_SECRET_KEY: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
          ENCRYPTION_SECRET_KEY: f3d87b231ddd6f50d99e227c5bc9b7cbb649387b321008df412fd73805ac2e32
          OKTA_ORG_URL: http://localhost:9000
          OKTA_API_TOKEN: oktatoken
          OKTA_CUSTOM_OAUTH_SERVER: oktaoauthserverid
          OKTA_CLIENT_ID: oktaclientid
          OKTA_CLIENT_SECRET: oktaclientsecret
          LOGGING_KINESIS_STREAM: ''
          EC2_INSTANCE_ID: ''
          # This is a public URL+key sent to Sentry on the client side
          # We disable Sentry for our tests
          SENTRY_DSN: ''
          REDIS_HOST: localhost
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_SSL_ON: false
          RATE_LIMITER_CONFIG: '{"enabled":true,"defaultBuckets":{"globalBucket":{"capacity":500,"addTokenMs":50}}}'
        with:
          build: yarn build
          start: yarn start, yarn mock-server
          wait-on: 'http://localhost:8861/healthcheck, http://localhost:9000/healthcheck'
          wait-on-timeout: 180
          quiet: true
          browser: chrome
          spec: cypress/integration/mocked/*.ts
