name: cypress
on: push
jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          NODE_ENV: development
        with:
          start: yarn cypress:ete
          wait-on: 'http://localhost:3030'
          wait-on-timeout: 180
          quiet: true
          browser: chrome
          spec: cypress/integration/ete/*.js
