name: tsc
on: push
jobs:
  jest:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run eslint
        run: yarn type-check
